//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace littleworld.Web.userTb {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtuserName;
		protected global::System.Web.UI.WebControls.TextBox txtuserEmail;
		protected global::System.Web.UI.WebControls.TextBox txtuserPwd;
		protected global::System.Web.UI.WebControls.TextBox txtheadImgUrl;
		protected global::System.Web.UI.WebControls.TextBox txtsex;
		protected global::System.Web.UI.WebControls.TextBox txtaddr;
		protected global::System.Web.UI.WebControls.TextBox txtage;
		protected global::System.Web.UI.WebControls.TextBox txtprimarySchool;
		protected global::System.Web.UI.WebControls.TextBox txtjuniorSchool;
		protected global::System.Web.UI.WebControls.TextBox txthighSchool;
		protected global::System.Web.UI.WebControls.TextBox txtcollegeSchool;
		protected global::System.Web.UI.WebControls.TextBox txtinterstID;
		protected global::System.Web.UI.WebControls.TextBox txtstate;
		protected global::System.Web.UI.WebControls.TextBox txtgroupID;
		protected global::System.Web.UI.WebControls.TextBox txtreprotNum;
		protected global::System.Web.UI.WebControls.TextBox txtskinID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
