//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace littleworld.Web.userTb {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluserID;
	protected global::System.Web.UI.WebControls.Label lbluserName;
	protected global::System.Web.UI.WebControls.Label lbluserEmail;
	protected global::System.Web.UI.WebControls.Label lbluserPwd;
	protected global::System.Web.UI.WebControls.Label lblheadImgUrl;
	protected global::System.Web.UI.WebControls.Label lblsex;
	protected global::System.Web.UI.WebControls.Label lbladdr;
	protected global::System.Web.UI.WebControls.Label lblage;
	protected global::System.Web.UI.WebControls.Label lblprimarySchool;
	protected global::System.Web.UI.WebControls.Label lbljuniorSchool;
	protected global::System.Web.UI.WebControls.Label lblhighSchool;
	protected global::System.Web.UI.WebControls.Label lblcollegeSchool;
	protected global::System.Web.UI.WebControls.Label lblinterstID;
	protected global::System.Web.UI.WebControls.Label lblstate;
	protected global::System.Web.UI.WebControls.Label lblgroupID;
	protected global::System.Web.UI.WebControls.Label lblreprotNum;
	protected global::System.Web.UI.WebControls.Label lblskinID;


       
    }
}
