//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace littleworld.Web.transmitTb {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtnoveltyID;
		protected global::System.Web.UI.WebControls.TextBox txttransmiterID;
		protected global::System.Web.UI.WebControls.TextBox txtpower;
		protected global::System.Web.UI.WebControls.TextBox txtcontents;
		protected global::System.Web.UI.WebControls.TextBox txttransmitTime;
		protected global::System.Web.UI.WebControls.TextBox txtstate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
