//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace littleworld.Web.photoTb {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtphotoID;
		protected global::System.Web.UI.WebControls.TextBox txtownID;
		protected global::System.Web.UI.WebControls.TextBox txtdescription;
		protected global::System.Web.UI.WebControls.TextBox txtimgUrl;
		protected global::System.Web.UI.WebControls.TextBox txtphotoGroupID;
		protected global::System.Web.UI.WebControls.TextBox txtcreatTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
