//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace littleworld.Web.noveltyTb {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtsenderID;
		protected global::System.Web.UI.WebControls.TextBox txtcontents;
		protected global::System.Web.UI.WebControls.TextBox txtstate;
		protected global::System.Web.UI.WebControls.TextBox txthasImgs;
		protected global::System.Web.UI.WebControls.TextBox txttypeID;
		protected global::System.Web.UI.WebControls.TextBox txtcommentNum;
		protected global::System.Web.UI.WebControls.TextBox txtsupportNum;
		protected global::System.Web.UI.WebControls.TextBox txtreportNum;
		protected global::System.Web.UI.WebControls.TextBox txttransmitNum;
		protected global::System.Web.UI.WebControls.TextBox txtpublishtime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
