//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace littleworld.Web.noveltyTb {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblnoveltyID;
	protected global::System.Web.UI.WebControls.Label lblsenderID;
	protected global::System.Web.UI.WebControls.Label lblcontents;
	protected global::System.Web.UI.WebControls.Label lblstate;
	protected global::System.Web.UI.WebControls.Label lblhasImgs;
	protected global::System.Web.UI.WebControls.Label lbltypeID;
	protected global::System.Web.UI.WebControls.Label lblcommentNum;
	protected global::System.Web.UI.WebControls.Label lblsupportNum;
	protected global::System.Web.UI.WebControls.Label lblreportNum;
	protected global::System.Web.UI.WebControls.Label lbltransmitNum;
	protected global::System.Web.UI.WebControls.Label lblpublishtime;


       
    }
}
